name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    name: Backend test
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./quirknotes/backend

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@v1
        with:
          mongodb-version: '4.4'
    
      - run: npm i
      - run: npm test
